### ISSUE TITLE
Improve UI / New UI Proposal

### ISSUE THREAD

**Issue by rumaan** [rumaan/nasa_apod_flutter#21]

**Comment by rumaan** [comment]
Going on in #20

**Comment by rumaan** [comment]
@melwinlobo18 Check out this design spec and let me know what you think. 
In the meantime please **post*( the ScreenShots of changes in the #20 PR. Let's discuss it here.


![design_spec](https://user-images.githubusercontent.com/18492868/66805951-ea0bcd00-ef43-11e9-8174-ce0ab1e96061.png)

Full res:
[design_spec.png.zip](https://github.com/rumaan/nasa_apod_flutter/files/3727633/design_spec.png.zip)

**Comment by melwinlobo18** [comment]
![APOD-Spec](https://user-images.githubusercontent.com/29202917/66807730-5a681d80-ef47-11e9-8a1c-10c051d3120c.png)

### Fonts Used
Title: PlayfairDisplay
Body: Montserrat

**Comment by rumaan** [comment]
That looks great. Can you change the background color in the detail screen to match with the home screen (black) and also tone down the white shadow below the card a bit.:smile:

**Comment by melwinlobo18** [comment]
Sure. I'll change the details screen to the one given in the design spec.

**Comment by rumaan** [comment]
> Sure. I'll change the details screen to the one given in the design spec.

Yeah sure. If possible just use the colours or fonts in the design spec.
Thanks

**Comment by melwinlobo18** [comment]
I have pushed the changes.

**Comment by rumaan** [comment]
Hey that i was a lil busy. I'll merge ASAP
