### ISSUE TITLE
Can't compile code.

### ISSUE THREAD

**Issue by srihariash999** [rumaan/nasa_apod_flutter#24]
I added the json file with the API key as suggested in the ReadMe. But, I still can't run the app.

These are the error messages I get.  

`Compiler message:
../../../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.1/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../../flutter/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/home/srihari/flutter/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/srihari/flutter/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
Finished with error: Gradle task assembleDebug failed with exit code 1
`

Also, these are the versions I use:

Flutter 1.12.11-pre.10 • channel master • https://github.com/flutter/flutter.git
Framework • revision 033b897be5 (3 days ago) • 2019-11-23 04:05:54 -0500
Engine • revision b6b54fd606
Tools • Dart 2.7.0

Can you help me solve this?

**Comment by srihariash999** [comment]
I figured out what all were closing errors, I fixed them I believe. I opened a PR with the changes.

**Comment by rumaan** [comment]
Thanks I'll look into it
