### ISSUE TITLE
Download High Resolution image Feature 

### ISSUE THREAD

**Issue by rumaan** [rumaan/nasa_apod_flutter#6]
- use `hdurl` field in the JSON response (some don't have it, so automatically download the `url` ones) 
- FAB in detail page does nothing as of now
- Suggestion to make it so that on click would dispatch a *background* task to download the image with a confirmation dialog

**Comment by payam-zahedi** [comment]
hi @rumaan, I would like to work on it. Can I use [Image_downloader](https://pub.dev/packages/image_downloader) package?

**Comment by rumaan** [comment]
Yeah sure go ahead. I think i already use that package just check again

**Comment by payam-zahedi** [comment]
@rumaan I think this issue has been solved. please check the code for fab button in detail page.

**Comment by rumaan** [comment]
Yeah it has been resolved ill close this asap.
