### ISSUE TITLE
Handle API Failures/Errors

### ISSUE THREAD

**Issue by rumaan** [rumaan/nasa_apod_flutter#8]
- Handle Errors/Exceptions Gracefully with relevant messages
- Support for Retries on API request fails
- Support for Proper messages on 429 Status code (Rate limit)

**Comment by payam-zahedi** [comment]
Hi @rumaan is this issue taken? if not i would like to work on it. i will create a branch "issue 10" for this issue. can u give me more explanation about second item in your issue.

Support for Retries on API request fails?

Thanks

**Comment by rumaan** [comment]
Yeah. @payam-zahedi You can go ahead work on it. 
By support for retires on api request fail I meant about say if the api request fails due to internet connectivity, possibly an option like "tap to retry"

**Comment by payam-zahedi** [comment]
ok, @rumaan. for "tap to retry" I will create a widget that shows a details Text and retry Button.
and for handle "Handle Errors/Exceptions Gracefully with relevant messages", I think I should create a util class for it. if u have any suggestions for where I should put my files or anything else please let me know.

**Comment by rumaan** [comment]
Yes. That would be great. :smile:
Moving over the handle apu errors logic to some other place (like it's own file) would be really helpful later on when writing tests.

**Comment by payam-zahedi** [comment]
Dear @rumaan, I've send a PR for this issue. please fell free to comment and ask any questions.

**Comment by rumaan** [comment]
Fixed #16
